### ISSUE TITLE
AssertionError: train_cfg specified in both outer field and model field 

### ISSUE THREAD

**Issue by PleasantPhoenix** [RunpeiDong/PointDistiller#8]
When I try to run CUDA_VISIBLE_DEVICES=0 python tools/train.py configs/pointpillars/hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class_student_4x.py --use-kd ，I encounter the following error message. How can I solve it?
2023-05-22 20:03:39,521 - mmdet - INFO - Set random seed to 0, deterministic: False
/home/k/KD/PointDistiller/mmdetection3d/mmdet3d/models/builder.py:53: UserWarning: train_cfg and test_cfg is deprecated, please specify them in model
  'please specify them in model', UserWarning)
Traceback (most recent call last):
  File "tools/train.py", line 294, in <module>
    main()
  File "tools/train.py", line 248, in main
    test_cfg=cfg.get('test_cfg'))
  File "/home/k/KD/PointDistiller/mmdetection3d/mmdet3d/models/builder.py", line 85, in build_model
    return build_detector(cfg, train_cfg=train_cfg, test_cfg=test_cfg)
  File "/home/k/KD/PointDistiller/mmdetection3d/mmdet3d/models/builder.py", line 55, in build_detector
    'train_cfg specified in both outer field and model field '
AssertionError: train_cfg specified in both outer field and model field

**Comment by RunpeiDong** [comment]
Hi @PleasantPhoenix,

Have you set up the environment following the `getting_started.md` instructions? I have not met this error. It seems the train_cfg or test_cfg is not specified, but the settings are already written in the config file you run. So I think there is something wrong with the config parsing, which may be caused if the environment is not set up correctly.

**Comment by PleasantPhoenix** [comment]
hello,After I comfirmed it again according to the getting_started.md file,the operation still reported the same error, and I found two train_cfg parameters defined in hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class_student_4x.py file,but only one  in other files.What do they refer to?In addition Iwould like to confirm with you whether I have modified the two files correctly.
![2023-05-23 17-30-29 的屏幕截图](https://github.com/RunpeiDong/PointDistiller/assets/86542147/66b07117-a61e-4631-b05a-afffa470306a)
![2023-05-23 17-31-15 的屏幕截图](https://github.com/RunpeiDong/PointDistiller/assets/86542147/26d3a646-a029-4bf0-92cf-e2a453961daf)
Finally when I try to run CUDA_VISIBLE_DEVICES=0 python tools/train.py configs/pointpillars/hv_pointpillars_secfpn_6x8_160e_kitti-3d-car_student_4x.py --use-kd ,I encounter the following error message,and I'm sure the .py file has kd parameter.
2023-05-23 16:40:32,505 - mmdet - INFO - Set random seed to 0, deterministic: False
/home/k/KD/mmdetection3d-1.0.0rc0/mmdet3d/models/dense_heads/anchor3d_head.py:86: UserWarning: dir_offset and dir_limit_offset will be depressed and be incorporated into box coder in the future
  'dir_offset and dir_limit_offset will be depressed and be '
Traceback (most recent call last):
  File "/home/k/anaconda3/envs/pd/lib/python3.6/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/home/k/KD/mmdetection3d-1.0.0rc0/mmdet3d/models/detectors/voxelnet.py", line 88, in __init__
    if self.kd_cfg is not None:
  File "/home/k/anaconda3/envs/pd/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1178, in __getattr__
    type(self).__name__, name))
AttributeError: 'VoxelNet' object has no attribute 'kd_cfg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 294, in <module>
    main()
  File "tools/train.py", line 248, in main
    test_cfg=cfg.get('test_cfg'))
  File "/home/k/KD/mmdetection3d-1.0.0rc0/mmdet3d/models/builder.py", line 85, in build_model
    return build_detector(cfg, train_cfg=train_cfg, test_cfg=test_cfg)
  File "/home/k/KD/mmdetection3d-1.0.0rc0/mmdet3d/models/builder.py", line 59, in build_detector
    cfg, default_args=dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/k/anaconda3/envs/pd/lib/python3.6/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/k/anaconda3/envs/pd/lib/python3.6/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/k/anaconda3/envs/pd/lib/python3.6/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
AttributeError: VoxelNet: 'VoxelNet' object has no attribute 'kd_cfg'

**Comment by RunpeiDong** [comment]
Hi @PleasantPhoenix,

- The files look good to me. I think there are no problems.
- The kd_cfg is a bug. You should add this line: 
`self.kd_cfg = train_cfg.get("kd_cfg", None)` before [here](https://github.com/RunpeiDong/PointDistiller/blob/04f973111740943591541e0327a8214611115094/mmdet3d/models/detectors/voxelnet.py#L88). Sorry, my bad. I have fixed it.
